name: todo
description: "A todo app with Dropbox sync."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  http: ^1.3.0
  intl: ^0.20.2
  collection: ^1.19.1
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  shared_preferences: ^2.3.4
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
